
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxlwhqlbxyuyujhqeyur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4bHdocWxieHl1eXVqaHFleXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMjAyNTMsImV4cCI6MjA1Mzc5NjI1M30.6TlBEqXOPZRgwhPrHQBYjMMVzmCTmCb-Q1-sNnFhVrc";

// The app key that identifies this specific app instance
export const APP_KEY = 'crd_main_app';

// Create the Supabase client with app context
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get the app ID
export const getAppId = async (): Promise<string | null> => {
  const { data, error } = await supabase
    .rpc('get_app_id', { p_app_key: APP_KEY });
  
  if (error) {
    console.error('Error getting app ID:', error);
    return null;
  }
  
  return data;
};
